# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12b66397eabcd1ac170e3467035c32ddc6c7f831ec1ed462f077ddcfc04330a40f632f21de6b91db06c14f2cc10dab81a30198bbdb63d8d9629263d03f412ba5

test:
  secret_key_base: d77c5f8e9ba6785dec31da2cf2bde9c033837eb753f508bebf9494a7733fc62bba7d01787c8f95a1926333cbf6d05f8ba1da5df9d7561230ef3a4aaf39f5f21a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
